const Colors = {
  primary: '#004DC8',
  secondary: '#36AA5D',
  red: '#BE4232',
  orange: '#DF9526',
  white: '#FFFFFF',
  black: '#000000',
  lightBlue: '#E8F1FF',
  lightGray: '#E8E8E9',
  inputGray: '#F1F4F8',
  paleBlue: '#FAFCFF',
  lightGrayishViolet: '#DFD4F6',
  veryDarkViolet: '#39216C',
  darkDesaturatedViolet: '#463767',
  veryLightGray: '#D9D9D9',
  grayishBlue: '#A4B1C4',
  veryDarkGray: '#5E5E5E',
  veryDarkBlue: '#1D3C6E',
  moderateBlue: '#3268BE',
  lightGrayishBlue: '#F3F6FC',
  lightGrayishRed: '#FCEFED',
  darkLimeGreen: '#74A47A',
  veryDarkLimeGreen: '#2E5A33',
  secondaryBackground: '#275296',
  veryPaleBlue: '#F6FAFF',
  darkPaleBlue: '#DBE9FF',
  veryLightGrayishBlue: '#ECF1F8',
  lightGrayishCyan: '#EBFBEF',
  lightGrayishLimeGreen: '#D5ECDA',
  veryPaleYellow: '#FFFCE5',
  lightGrayishYellow: '#E8E4BF',
  veryPaleOrange: '#FFE7D3',
  lightPaleBlue: '#EEF4FF',
  veryPaleViolet: '#F1E4FF',
  moderatetGrayishBlue: '#CADAF1',
  themeBlue: '#004DC8',
  textBlack: '#111111',
};

export default Colors;

//#121212 -- black shade
// 5E5E5E -- grey shade
